preprocessing:
- person("who").: List all the persons mentioned including me if indirectly included.
- cuisine_preferences("who", "country").: For each person, list any restaurant preferences.
- want_food("who", "what").: For each person, list what they want to eat.

knowledge_base: |
  can_go_together(X,Y,Z) :- person(X), person(Y), X < Y, want_food(X,Z), want_food(Y,Z).
  can_go_together(X,Y,Z) :- person(X), person(Y), X < Y, cuisine_preferences(X,Z), cuisine_preferences(Y,Z).
  #show can_go_together/3.

postprocessing:
- _: Explain the facts in a human readable way, as a paragraph.
- can_go_together("person 1", "person 2", "cuisine preference"): Say that "person 1" can go with "person 2" to eat "cuisine preference".