from dataclasses import dataclass
from utils.yaml_to_csv import GrammarsBuilder
from typeguard import typechecked
from pydantic import BaseModel, Field

import re
from utils.class_builder import ClassBuilder
from utils.llm_handler import LLMHandler

@typechecked
@dataclass(frozen=False)
class EvaluateInput:

    ## TODO: Move part of this logic to a better place (Consider creating a class Reasoning)

    def __init__ (self, _llm_models, config, b_config):
        #self.__llm_instance_extractor = LLMHandler(_llm_models[0], """You are an expert in data extraction.""")
        self.__llm_instance_reasoner = LLMHandler(_llm_models[1], """You are an expert in data description.""")
        self.__llm_instance_extractor = LLMHandler(_llm_models[0], b_config["init"])
        self.__classes = ClassBuilder(config['preprocessing']).get_classes()
        self.__grammars = GrammarsBuilder(config['preprocessing']).get_grammars()
        self.__config = config
        self.__b_config = b_config

        print("Grammars:", self.__grammars)

        #self.__reasoning_out = {}

    def __filter_asp_atoms__(self, req: str) -> str:
        return " ".join(re.findall(r"\b[a-zA-Z][\w_]*\([^)]*\)\.", req))

    def __extract_atom_descr(self) -> tuple[list, list, str]:  
        questions = self.__config['preprocessing']
        extra_context = ""
        atom_description = []
        atoms = []

        for q in questions:

            q_key, q_value = list(q.items())[0]

            if q_key == '_':
                extra_context += q_value + '\n'

            else:
                atoms.append(q_key.replace(":str", "").replace(":int", ""))
                atom_description.append(q_value.replace("\n", ""))

        return atoms, atom_description, extra_context
    
    
    def __natural_to_asp__(self, _input: str, _format:str) -> str:
        """
            Convert natural language input to ASP (Answer Set Programming) format.
            
            This method takes a natural language input provided by the user and converts it
            into ASP format using the invoke_llm from the LLMHandler class. It preprocesses
            the input by performing input seasoning to extract the atoms contained into the config file,
            and then filters the ASP atoms from the response generated by the LLMHandler.
            
            Parameters:
                user_input (str): The natural language input provided by the user.
                
            Returns:
                str: The ASP-formatted output generated from the natural language input.
        """

        result_atoms = ""

        atom_to_extract, atom_descriptions, extra_context = self.__extract_atom_descr()
        _class_dict = self.__classes
        
        # Get only the main classes and not the list of classes
        main_class = [main_class for main_class in _class_dict.items() if "list_" not in main_class[0]]

        #for each main_class, define the fields and annotations
        dict_ = {f"{class_[0]}":  Field(title=class_[0], description=atom_descriptions[idx], default=None) for idx, class_ in enumerate(main_class)}
        dict_["__annotations__"] = {f"{name}": list[cls] for name, cls in main_class}

        # Create the atoms class dynamically during runtime
        atoms_class =  type(
            "atoms",
            (BaseModel,), 
            dict_
        )

        mapping = self.__b_config["mapping"]
        mapping = mapping.replace("{input}", _input)
        mapping = mapping.replace("{instructions}", "\n".join(atom_descriptions))
        mapping = mapping.replace("{atom}", " ".join(atom_to_extract))
        real_context = self.__b_config["context"].replace("{context}", f"{_format}")

        #print(extra_context)
        # Invoke the constrained llm with json schema and return the atoms
        #refined_instruction = self.__llm_instance.invoke_llm([f"Reason over the text. List all the informations. No formatting, just the instructions.\n{_format}"])
        #print(refined_instruction)
        response =  self.__llm_instance_extractor.invoke_llm_constrained(mapping, atoms_class, real_context)

        # from each main_class inside a list of main_class, extract the value of the parameters and use the __str__ method 
        # defined during the class_builder to create the atom structure

        if response is not None:
            for c, _ in main_class:
                list_of_atoms = response.dict().get(f"{c}")

                if list_of_atoms:
                    for atoms in list_of_atoms:
                        if atoms is not None:
                            result_atoms += str(_class_dict[c](**atoms)) + "\n"

        return result_atoms
    
    def __natural_to_asp_single_cot__(self, _input: str, _format:str) -> str:
        """
            Convert natural language input to ASP (Answer Set Programming) format.
            
            This method takes a natural language input provided by the user and converts it
            into ASP format using the invoke_llm from the LLMHandler class. It preprocesses
            the input by performing input seasoning to extract the atoms contained into the config file,
            and then filters the ASP atoms from the response generated by the LLMHandler.
            
            Parameters:
                user_input (str): The natural language input provided by the user.
                
            Returns:
                str: The ASP-formatted output generated from the natural language input.
        """

        result_atoms = ""

        atom_to_extract, atom_descriptions, extra_context = self.__extract_atom_descr()
        _class_dict = self.__classes
        
        # Get only the main classes and not the list of classes
        main_class = [main_class for main_class in _class_dict.items() if "list_" not in main_class[0]]

        #for each main_class, define the fields and annotations
        dict_ = {f"{class_[0]}":  Field(title=class_[0], description=atom_descriptions[idx], default=None) for idx, class_ in enumerate(main_class)}
        dict_["__annotations__"] = {f"{name}": list[cls] for name, cls in main_class}

        # Create the atoms class dynamically during runtime
        atoms_class =  type(
            "atoms",
            (BaseModel,), 
            dict_
        )

        joined_descriptions = "\n".join(atom_descriptions)

        reason_prompt = f"""
                Provide a **detailed**, clear and analytical explanation, of how to extract the data following this description: {joined_descriptions}.
                Focus on the reasoning process, including what to look for and how to interpret the provided data.
                **Ensure and prove** that the output satisfies the description.
                **Don't output useless comments**.
                Do **not** include any code or direct solution—only a plain-text explanation of the thought process: `{_input}`.
            """

        refined_instruction = self.__llm_instance_reasoner.invoke_llm([reason_prompt])

        print(refined_instruction)

        mapping = self.__b_config["mapping"]
        mapping = mapping.replace("{input}", _input)
        mapping = mapping.replace("{instructions}", refined_instruction)
        mapping = mapping.replace("{atom}", " ".join(atom_to_extract))
        real_context = self.__b_config["context"].replace("{context}", f"{_format}")

        #print(extra_context)
        # Invoke the constrained llm with json schema and return the atoms
        #refined_instruction = self.__llm_instance.invoke_llm([f"Reason over the text. List all the informations. No formatting, just the instructions.\n{_format}"])
        #print(refined_instruction)
        response =  self.__llm_instance_extractor.invoke_llm_constrained(mapping, atoms_class, real_context)

        # from each main_class inside a list of main_class, extract the value of the parameters and use the __str__ method 
        # defined during the class_builder to create the atom structure

        if response is not None:
            for c, _ in main_class:
                list_of_atoms = response.dict().get(f"{c}")

                if list_of_atoms:
                    for atoms in list_of_atoms:
                        if atoms is not None:
                            result_atoms += str(_class_dict[c](**atoms)) + "\n"

        return result_atoms

    
    def __natural_no_reason_to_asp_multi__(self, _input: str, _format:str) -> str:

        result_atoms = ""

        atoms, atom_descriptions, extra_context = self.__extract_atom_descr()
        print(atoms)

        _class_dict = self.__classes
        _list = [list_class for list_class in _class_dict.items() if "list_" in list_class[0]]
        main_class = [main_class[0] for main_class in _class_dict.items() if "list_" not in main_class[0]]

        mapping = self.__b_config["mapping"]
        mapping = mapping.replace("{input}", _input)
        
        for i, descr in enumerate(atom_descriptions):

            real_context = self.__b_config["context"].replace("{context}", f"{_format}")


            reason_prompt = f"""
                Provide a **detailed**, clear and analytical explanation, of how to extract the data following this description: `{descr}`.
                Do **not** include any code or direct solution—only a plain-text explanation of the thought process.
                Focus on what to look for and how to interpret the data in input: `{_input}`
            """

            #reason_out = self.__llm_instance_reasoner.invoke_llm([_format, reason_prompt])
            
            appl_mapping = mapping.replace("{instructions}", descr)
            appl_mapping = appl_mapping.replace("{atom}", atoms[i])
            print(appl_mapping)

            response = self.__llm_instance_extractor.invoke_llm_constrained(appl_mapping, _list[i][1], real_context)

            if response != None:

                atom_list = response.dict().get(f"list_{main_class[i]}")

                if atom_list != None:
                    for atom in atom_list:
                        if atom != None:
                            class_name = main_class[i]
                            class_instance = str(_class_dict[class_name](**atom))

                            result_atoms += class_instance + "\n"
        
        return result_atoms

    def __natural_no_reason_to_asp_single__(self, _input: str, _format:str) -> str:

        result_atoms = ""

        atoms, atom_descriptions, extra_context = self.__extract_atom_descr()
        print(atoms)

        _class_dict = self.__classes
        _list = [list_class for list_class in _class_dict.items() if "list_" in list_class[0]]
        main_class = [main_class[0] for main_class in _class_dict.items() if "list_" not in main_class[0]]

        mapping = self.__b_config["mapping"]
        mapping = mapping.replace("{input}", _input)
        
        for i, descr in enumerate(atom_descriptions):

            real_context = self.__b_config["context"].replace("{context}", f"{_format}")

            print(real_context)
            
            appl_mapping = mapping.replace("{instructions}", descr)
            appl_mapping = appl_mapping.replace("{atom}", atoms[i])

            print(appl_mapping)

            response = self.__llm_instance_extractor.invoke_llm_constrained(appl_mapping , _list[i][1], real_context)

            if response != None:

                # check if response corrisponds to what we want, otherwise edit the reasoned extration
                #if descr not in reasoning_map:
                #    check_prompt = f"""Check if this result '{response}' corresponds to what the user asked: {_input}. 
                #            Your job is to return a more general, refined reasoning, starting from this one. 
                #            Do not add extra commentary. Original reasoning:\n{reason_out}"""

                #    check_res = self.__llm_instance_extractor.invoke_llm([check_prompt])
                #    reasoning_map[descr] = check_res

                atom_list = response.dict().get(f"list_{main_class[i]}")

                if atom_list != None:
                    for atom in atom_list:
                        if atom != None:
                            class_name = main_class[i]
                            class_instance = str(_class_dict[class_name](**atom))

                            result_atoms += class_instance + "\n"
        
        return result_atoms

    def __natural_no_reason_to_asp_multi_csv__(self, _input: str, _format:str) -> str:

        result_atoms = ""

        atoms, atom_descriptions, extra_context = self.__extract_atom_descr()
        print(atoms)

        _class_dict = self.__classes
        _list = [list_class for list_class in _class_dict.items() if "list_" in list_class[0]]
        main_class = [main_class[0] for main_class in _class_dict.items() if "list_" not in main_class[0]]

        mapping = self.__b_config["mapping"]
        mapping = mapping.replace("{input}", _input)
        
        for i, descr in enumerate(atom_descriptions):
            grammar, example, res_to_asp = self.__grammars[main_class[i]]

            real_context = self.__b_config["context"].replace("{context}", f"{_format}")
            
            appl_mapping = mapping.replace("{instructions}", descr)
            appl_mapping = appl_mapping.replace("{atom}", example)


            response = self.__llm_instance_extractor.invoke_llm_constrained(appl_mapping, grammar, real_context)

            if response != None or response != "":
                for atom in response.split("\n"):
                    if atom != "":
                        result_atoms += res_to_asp(atom) + "\n"
        
        return result_atoms

    def run(self, _input:str, _format:str) -> str:
        """
            Run the input handler to convert the user input to ASP format.
            
            This method takes user input and converts it to ASP format using the natural_to_asp method.
            It then returns the ASP-formatted output.
                
            Returns:
                str: The ASP-formatted output generated from the user input.
        """
        response = self.__natural_no_reason_to_asp_multi_csv__(_input, _format)

        return self.__filter_asp_atoms__(response)
