from dataclasses import dataclass
from typeguard import typechecked
from pydantic import BaseModel, Field

import re
from utils.class_builder import ClassBuilder
from utils.llm_handler import LLMHandler

@typechecked
@dataclass(frozen=False)
class EvaluateInput:

    def __post_init__ (self, _llm_model, config):
        self.__llm_instance = LLMHandler(_llm_model, "Extract only the relevant information from user_prompt following the description of each atom.")
        self.__classes = ClassBuilder(config['preprocessing']).get_classes()

    def __filter_asp_atoms__(self, req: str) -> str:
        return " ".join(re.findall(r"\b[a-zA-Z][\w_]*\([^)]*\)\.", req))

    def __extract_atom_descr(self) -> list:  
        questions = self.__config['preprocessing']
        extra_context = ""
        atom_description = []

        for q in questions:

            q_key, q_value = list(q.items())[0]

            if q_key == '_':
                extra_context += q_value + '\n'

            else:
                atom_description.append(q_value)

        return atom_description, extra_context
    
    
    def __natural_to_asp__(self, user_input: str) -> str:
        """
            Convert natural language input to ASP (Answer Set Programming) format.
            
            This method takes a natural language input provided by the user and converts it
            into ASP format using the invoke_llm from the LLMHandler class. It preprocesses
            the input by performing input seasoning to extract the atoms contained into the config file,
            and then filters the ASP atoms from the response generated by the LLMHandler.
            
            Parameters:
                user_input (str): The natural language input provided by the user.
                
            Returns:
                str: The ASP-formatted output generated from the natural language input.
        """

        result_atoms = ""

        atom_descriptions, extra_context = self.__extract_atom_descr()
        _class_dict = self.__classes
        
        # Get only the main classes and not the list of classes
        main_class = [main_class for main_class in _class_dict.items() if "list_" not in main_class[0]]

        #for each main_class, define the fields and annotations
        dict_ = {f"g_{class_[0]}":  Field(title=class_[0], description=atom_descriptions[idx], ) for idx, class_ in enumerate(main_class)}
        dict_["__annotations__"] = {f"g_{name}": list[cls] | None for name, cls in main_class}

        # Create the atoms class dynamically during runtime
        atoms_class =  type(
            "atoms_class",
            (BaseModel,), 
            dict_
        )
        
        # Invoke the constrained llm with json schema and return the atoms
        response =  self.__llm_instance.invoke_llm_constrained(user_input, atoms_class, command = extra_context)

        # from each main_class inside a list of main_class, extract the value of the parameters and use the __str__ method 
        # defined during the class_builder to create the atom structure

        for c, _ in main_class:
            for atoms in response.dict().get(f"g_{c}"):
                    result_atoms += str(_class_dict[c](**atoms)) + "\n"

        return result_atoms
    

    def run(self, custom_input = "", TRAIN_ON: bool = False) -> str:
        """
            Run the input handler to convert the user input to ASP format.
            
            This method takes user input and converts it to ASP format using the natural_to_asp method.
            It then returns the ASP-formatted output.
                
            Returns:
                str: The ASP-formatted output generated from the user input.
        """
        
        self.user_input = custom_input
        response = self.__natural_to_asp__(self.user_input)

        return self.__filter_asp_atoms__(response)
